main:
  database_path: './patients.sqlite3'
  short_output_string: '{hb}\t{wbc}\t{platelets}\t{sodium}\t{potassium}\t{egfr}\t{creatinine}\t{crp}'
  default_output_string: 'Respiratory extended (RTF)'
  log_clipboard_events: no
  paste_text_with_rtf: yes
  non_green_bolding: yes
  output_strings:
    - name: 'short'
      type: 'text/plain'
      string: '{hb}\t{wbc}\t{platelets}\t{sodium}\t{potassium}\t{egfr}\t{creatinine}\t{crp}'
    - name: 'long'
      type: 'text/plain'
      string: '- Hb {hb}, Plt {platelets}, WBC {wbc}

      - Na {sodium}, K {potassium}

      - Ca {calcium}, Mg {magnesium}, Ph {phosphate}

      - eGFR {egfr}, Cr {creatinine}

      - ALT {alt}, AST {ast}, GGT {ggt}, ALP {alp}

      - CRP {crp}
      
      - LDH {ldh}'
    - name: 'extra long'
      type: 'text/plain'
      string: '- Hb {hb}, Plt {platelets}, WBC {wbc}

      - Neuts {neut}, Lymphs {lymph}, Monos {mono}, Eosins {eosin}, Basos {baso}

      - eGFR {egfr}, Cr {creatinine}

      - ALT {alt}, AST {ast}, GGT {ggt}, ALP {alp}

      - Na {sodium}, K {potassium}

      - Ca {calcium}, Mg {magnesium}, Ph {phosphate}

      - CRP {crp}, ESR {esr}
      
      - LDH {ldh}

      - INR {inr}'
    - name: 'extra long (RTF)'
      type: 'application/rtf'
      string: '{{\\rtf\\ansi

      {{\\fonttbl{{\\f0\\fmodern Courier New;}}{{\\f2 Tahoma;}}}}

      {{\\colortbl\\red37\\green37\\blue37;\\red37\\green37\\blue37;\\red128\\green128\\blue0;\\red128\\green0\\blue0;\\red128\\green64\\blue0;\\red0\\green0\\blue255;\\red255\\green0\\blue0;
\\red255\\green255\\blue0;\\red255\\green255\\blue255;}}

      \\pard\\plain

      \\f0 - Hb {hb}, Plt {platelets}, WBC {wbc}

      \\par

      - Neuts {neut}, Lymphs {lymph}, Monos {mono}, Eosins {eosin}, Basos {baso}

      \\par
      
      - eGFR {egfr}, Cr {creatinine}

      \\par

      - ALT {alt}, AST {ast}, GGT {ggt}, ALP {alp}

      \\par

      - Na {sodium}, K {potassium}

      \\par

      - Ca {calcium}, Mg {magnesium}, Ph {phosphate}

      \\par

      - CRP {crp}, ESR {esr}

      \\par

      - LDH {ldh}

      \\par

      - INR {inr}

      }}'
    - name: 'Respiratory extended (RTF)'
      type: 'application/rtf'
      string: '{{\\rtf\\ansi

      {{\\fonttbl{{\\f0\\fmodern Courier New;}}{{\\f2 Tahoma;}}}}

      {{\\colortbl\\red37\\green37\\blue37;\\red37\\green37\\blue37;\\red128\\green128\\blue0;\\red128\\green0\\blue0;\\red128\\green64\\blue0;\\red0\\green0\\blue255;\\red255\\green0\\blue0;
\\red255\\green255\\blue0;\\red255\\green255\\blue255;}}

      \\pard\\plain

      \\f0 - Hb {hb}, Plt {platelets}, WBC {wbc}

      \\par

      - Neuts {neut}, Lymphs {lymph}, Monos {mono}, Eosins {eosin}, Basos {baso}

      \\par
      
      - eGFR {egfr}, Cr {creatinine}

      \\par

      - ALT {alt}, AST {ast}, GGT {ggt}, ALP {alp}

      \\par

      - Na {sodium}, K {potassium}

      \\par

      - Ca {calcium}, Mg {magnesium}, Ph {phosphate}

      \\par

      - Bicarbonate {bicarb}

      \\par

      - Albumin {albumin}

      \\par

      - CRP {crp}

      \\par

      - ESR {esr}

      \\par

      - LDH {ldh}

      \\par

      - INR {inr}

      \\par

      - VBG : pH {ph}, pCO2 {pco2}, HCO3 {hco3}, Lactate {lactate}, pO2 {po2}, O2 Sat. {o2sat}%

      }}'
  match_patterns:
    - name: 'hb'
      regex: 'Hgb\s+:\s+(\d+)\s+[ HLC]'
    - name: 'wbc'
      regex: '[EW]BC\s+:\s+([0-9\.]+)\s+[ HLC]'
    - name: 'platelets'
      regex: 'PLT\s+:\s+(\d+)\s+[ HLC]'
    - name: 'sodium'
      regex: 'Sodium\s+(\d+)\s+'
    - name: 'potassium'
      regex: 'Potassium\s+([0-9\.]+)\s+'
    - name: 'magnesium'
      regex: 'Magnesium\s+([0-9\.]+)\s+'
    - name: 'calcium'
      regex: 'Corr Ca\s+([0-9\.]+)\s+'
    - name: 'phosphate'
      regex: 'Phosphate\s+([0-9\.]+)\s+'
    - name: 'egfr'
      regex: 'eGFR\s+(\<?\>?\s*\d+)\s+'
    - name: 'creatinine'
      regex: 'Creatinine\s+(\<?\>?\s*\d+)\s+'
    - name: 'crp'
      regex: 'CRP\s+(\<?[0-9\.]+)'
    - name: 'ast'
      regex: 'AST\s+(\d+)'
    - name: 'alt'
      regex: 'ALT\s+(\d+)'
    - name: 'ggt'
      regex: 'Gamma GT\s+(\d+)'
    - name: 'alp'
      regex: 'ALP\s+(\d+)'
    - name: 'ldh'
      regex: 'LD\s+(\d+)'
    - name: 'inr'
      regex: 'INR\s+([0-9\.]+)'
    - name: 'esr'
      regex: 'ESR\s+(\d+)'
    - name: 'neut'
      regex: 'Neut.*?:\s+([0-9\.]+)'
    - name: 'lymph'
      regex: 'Lymph.*?:\s+([0-9\.]+)'
    - name: 'mono'
      regex: 'Mono.*?:\s+([0-9\.]+)'
    - name: 'eosin'
      regex: 'Eosin.*?:\s+([0-9\.]+)'
    - name: 'baso'
      regex: 'Baso.*?:\s+([0-9\.]+)'
    - name: 'freet4'
      regex: 'Free T4.*?:\s+([0-9\.]+)'
    - name: 'tsh'
      regex: 'TSH\s+([0-9\.]+)'
    - name: 'b12'
      regex: 'Vitamin B12\s+([0-9\.]+)'
    - name: 'folate'
      regex: 'Folate\s+([0-9\.]+)'
    - name: 'vitd'
      regex: '25-Hydroxy-Vitamin D\s+([0-9\.]+)'
    - name: 'iron'
      regex: 'Iron\s+(\<?\>?\s*[0-9\.]+)'
    - name: 'transferrin'
      regex: 'Transferrin\s+([0-9\.]+)'
    - name: 'transferrinsat'
      regex: 'Transferrin Saturation\s+(\<?\>?\s*[0-9\.]+)'
    - name: 'ferritin'
      regex: 'Ferritin\s+([0-9\.]+)'
    - name: 'albumin'
      regex: 'Albumin\s+([0-9]+)'
    - name: 'bicarb'
      regex: 'Bicarb\.\s+([0-9\.]+)'
    - name: 'ph'
      regex: 'pH\s+([0-9\.]+)'
    - name: 'pco2'
      regex: 'pCO2\s+([0-9\.]+)'
    - name: 'po2'
      regex: 'p02\s+([0-9\.]+)'
    - name: 'o2sat'
      regex: 'O2 Sat\.\s+([0-9\.]+)'
    - name: 'lactate'
      regex: 'Lact\s+([0-9\.]+)'
    - name: 'hco3'
      regex: 'HCO3-\s+([0-9\.]+)'
auslab:
  normal:
    name: normal
    debug: yes

    screenshot_y_border_max: 60
    screenshot_x_border_max: 15

    border_error_margin: 0

    header_x_start: 56
    header_y_start: 74

    header_x_end: 979
    header_y_end: 156

    header_char_num: 77
    header_line_num: 3

    line_spacing: 7

    line_height: 23
    char_width: 12

    condensed_line_height: 23
    condensed_char_width: 8

    central_panel_non_condensed_x_left_margin: 32
    central_panel_non_condensed_x_right_margin: 16

    central_panel_y_start: 194
    central_panel_y_end: 668

    f1_normal_template_path: 'F1_normal.png'
    f1_condensed_template_path: 'F1_condensed.png'

    template_file_path: './templates-normal.dat'

  large:
    name: large
    debug: yes

    screenshot_y_border_max: 60
    screenshot_x_border_max: 6

    border_error_margin: 25

    header_x_start: 70
    header_y_start: 92

    header_x_end: 1224
    header_y_end: 195

    header_char_num: 77
    header_line_num: 3

    line_spacing: 8.5

    line_height: 29
    char_width: 15

    condensed_line_height: 29
    condensed_char_width: 10

    central_panel_non_condensed_x_left_margin: 40
    central_panel_non_condensed_x_right_margin: 20

    central_panel_y_start: 242
    central_panel_y_end: 835

    f1_normal_template_path: 'F1_large_normal.png'
    f1_condensed_template_path: 'F1_large_condensed.png'

    template_file_path: './templates-large.dat'