main:
  database_path: './patients.sqlite3'
  short_output_string: '{hb}\t{wbc}\t{platelets}\t{sodium}\t{potassium}\t{egfr}\t{creatinine}\t{crp}'
  output_strings:
    - name: 'short'
      string: '{hb}\t{wbc}\t{platelets}\t{sodium}\t{potassium}\t{egfr}\t{creatinine}\t{crp}'
    - name: 'long'
      string: '- Hb {hb}, Plt {platelets}, WBC {wbc}

      - Na {sodium}, K {potassium}

      - Ca {calcium}, Mg {magnesium}, Ph {phosphate}

      - eGFR {egfr}, Cr {creatinine}

      - ALT {alt}, AST {ast}, GGT {ggt}, ALP {alp}

      - CRP {crp}
      
      - LDH {ldh}'
auslab:
  template_file_path: './templates-retrain.dat'

  screenshot_y_border_max: 60
  screenshot_x_border_max: 15

  header_x_start: 56
  header_y_start: 74

  header_x_end: 979
  header_y_end: 156

  header_char_num: 77
  header_line_num: 3

  line_spacing: 7

  line_height: 23
  char_width: 12

  condensed_line_height: 23
  condensed_char_width: 8

  central_panel_y_start: 194
  central_panel_y_end: 668