main:
  database_path: './patients.sqlite3'
  short_output_string: '{hb}\t{wbc}\t{platelets}\t{sodium}\t{potassium}\t{egfr}\t{creatinine}\t{crp}'
  output_strings:
    - name: 'short'
      string: '{hb}\t{wbc}\t{platelets}\t{sodium}\t{potassium}\t{egfr}\t{creatinine}\t{crp}'
    - name: 'long'
      string: '- Hb {hb}, Plt {platelets}, WBC {wbc}

      - Na {sodium}, K {potassium}

      - Ca {calcium}, Mg {magnesium}, Ph {phosphate}

      - eGFR {egfr}, Cr {creatinine}

      - ALT {alt}, AST {ast}, GGT {ggt}, ALP {alp}

      - CRP {crp}
      
      - LDH {ldh}'
    - name: 'extra long'
      string: '- Hb {hb}, Plt {platelets}, WBC {wbc}

      - Neuts {neut}, Lymphs {lymph}, Monos {mono}, Eosins {eosin}, Basos {baso}

      - CRP {crp}, ESR {esr}
      
      - eGFR {egfr}, Cr {creatinine}

      - ALT {alt}, AST {ast}, GGT {ggt}, ALP {alp}

      - Na {sodium}, K {potassium}

      - Ca {calcium}, Mg {magnesium}, Ph {phosphate}

      - LDH {ldh}

      - INR {inr}'
auslab:
  normal:
    name: normal
    debug: yes

    screenshot_y_border_max: 60
    screenshot_x_border_max: 15

    border_error_margin: 0

    header_x_start: 56
    header_y_start: 74

    header_x_end: 979
    header_y_end: 156

    header_char_num: 77
    header_line_num: 3

    line_spacing: 7

    line_height: 23
    char_width: 12

    condensed_line_height: 23
    condensed_char_width: 8

    central_panel_y_start: 194
    central_panel_y_end: 668

    f1_normal_template_path: 'auslab/F1_normal.png'
    f1_condensed_template_path: 'auslab/F1_condensed.png'

    template_file_path: './templates-normal.dat'

  large:
    name: large
    debug: yes

    screenshot_y_border_max: 60
    screenshot_x_border_max: 6

    border_error_margin: 25

    header_x_start: 70
    header_y_start: 92

    header_x_end: 1224
    header_y_end: 195

    header_char_num: 77
    header_line_num: 3

    line_spacing: 8.5

    line_height: 29
    char_width: 15

    condensed_line_height: 29
    condensed_char_width: 10

    central_panel_y_start: 242
    central_panel_y_end: 835

    f1_normal_template_path: 'auslab/F1_large_normal.png'
    f1_condensed_template_path: 'auslab/F1_large_condensed.png'

    template_file_path: './templates-large.dat'